### ISSUE TITLE
mysql problems

### ISSUE THREAD

**Issue by Captainpax** [TechnicallyCoded/Inventory-Rollback-Plus#112]
First great pl, been usinging it for years and has been a life saver.
I'm setting up the MySQL part and I get this error. You able to help with this?

[15:31:52] [Server thread/INFO]: [InventoryRollbackPlus] Enabling InventoryRollbackPlus v1.6.8
[15:33:22] [Server thread/WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[15:33:22] [Server thread/WARN]:
[15:33:22] [Server thread/WARN]: The last packet successfully received from the server was 90,107 milliseconds ago. The last packet sent successfully to the server was 90,107 milliseconds ago.
[15:33:22] [Server thread/WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
[15:33:22] [Server thread/WARN]: at InventoryRollbackPlus-1.6.8.jar//me.danjono.inventoryrollback.data.MySQL.createTables(MySQL.java:126)
[15:33:22] [Server thread/WARN]: at InventoryRollbackPlus-1.6.8.jar//me.danjono.inventoryrollback.InventoryRollback.startupTasks(InventoryRollback.java:96)
[15:33:22] [Server thread/WARN]: at InventoryRollbackPlus-1.6.8.jar//com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus.onEnable(InventoryRollbackPlus.java:63)
[15:33:22] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:33:22] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[15:33:22] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[15:33:22] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[15:33:22] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[15:33:22] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[15:33:22] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[15:33:22] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[15:33:22] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[15:33:22] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[15:33:22] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[15:33:22] [Server thread/WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[15:33:22] [Server thread/WARN]:
[15:33:22] [Server thread/WARN]: The last packet successfully received from the server was 90,107 milliseconds ago. The last packet sent successfully to the server was 90,107 milliseconds ago.
[15:33:22] [Server thread/WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:33:22] [Server thread/WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[15:33:22] [Server thread/WARN]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:33:22] [Server thread/WARN]: at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[15:33:22] [Server thread/WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:581)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:761)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:700)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1051)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
[15:33:22] [Server thread/WARN]: ... 18 more
[15:33:22] [Server thread/WARN]: Caused by: java.net.SocketTimeoutException: Read timed out
[15:33:22] [Server thread/WARN]: at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
[15:33:22] [Server thread/WARN]: at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
[15:33:22] [Server thread/WARN]: at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[15:33:22] [Server thread/WARN]: at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[15:33:22] [Server thread/WARN]: at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[15:33:22] [Server thread/WARN]: at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
[15:33:22] [Server thread/WARN]: at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
[15:33:22] [Server thread/WARN]: at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
[15:33:22] [Server thread/WARN]: at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1460)
[15:33:22] [Server thread/WARN]: at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064)
[15:33:22] [Server thread/WARN]: at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
[15:33:22] [Server thread/WARN]: at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:575)
[15:33:22] [Server thread/WARN]: ... 23 more
[15:33:22] [Server thread/INFO]: [InventoryRollbackPlus] Inventory backup data is set to save to: MySQL
[15:33:22] [Server thread/INFO]: [InventoryRollbackPlus] bStats are enabled

This is the log

**Comment by Captainpax** [comment]
I'm sure I'm dumb somewhere just needed to be pointed in the right direction.

**Comment by TechnicallyCoded** [comment]
Please attach a link to a pastebin or downloadable file of the entire log. This is quite hard to read and not enough information.

**Comment by TechnicallyCoded** [comment]
According to what I see so far: `Caused by: java.net.SocketTimeoutException: Read timed out`
Most likely that you are using the wrong IP, wrong port, or a firewall rule is blocking you. Everyone uses "libraries" in their plugins that handle SQL connections for us, which means I am using exactly the same thing everyone else would be using... There is most likely nothing I can do to fix anything other than guide you to fix whatever misconfiguration you have.

**Comment by TechnicallyCoded** [comment]
Closed due to no reply
