### ISSUE TITLE
[BUG]I don't know what bug this is, or how I can fix it.

### ISSUE THREAD

**Issue by qeqwzcx** [TechnicallyCoded/Inventory-Rollback-Plus#122]
### Bug description:
I don't know what bug this is or what will happen. Occurs when players cross servers.

### Server details:
 - Server type & version:   waterfall-1.19-510 & Paper(307) 1.19.2-R0.1-SNAPSHOT
 - InventoryRollbackPlus version: Running InventoryRollbackPlus v1.6.8

### How to reproduce:
This occasionally occurs when players are cross server.

### What was expected:
N/A

### Screenshots, logs & other:
[This is a server.]
[02:08:35 WARN]: [InventoryRollbackPlus] Plugin InventoryRollbackPlus v1.6.8 generated an exception while executing task 13066920
java.lang.IllegalStateException: Unable to save item stacks.
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:154) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at me.danjono.inventoryrollback.data.MySQL.setMainInventory(MySQL.java:236) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at me.danjono.inventoryrollback.data.PlayerData.setMainInventory(PlayerData.java:147) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.lambda$createSave$1(SaveInventory.java:96) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: swallow=2 and swallow=2
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1515) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1435) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1411) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1157) ~[?:?]
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1391) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191) ~[?:?]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354) ~[?:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:148) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        ... 9 more
[02:08:35 WARN]: [InventoryRollbackPlus] Plugin InventoryRollbackPlus v1.6.8 generated an exception while executing task 13067028
java.lang.IllegalStateException: Unable to save item stacks.
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:154) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at me.danjono.inventoryrollback.data.MySQL.setMainInventory(MySQL.java:236) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at me.danjono.inventoryrollback.data.PlayerData.setMainInventory(PlayerData.java:147) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.lambda$createSave$1(SaveInventory.java:96) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: swallow=2 and swallow=2
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1515) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1435) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1411) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1157) ~[?:?]
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1391) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191) ~[?:?]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354) ~[?:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:148) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        ... 9 more
[This is another one server.]
[02:08:35 WARN]: [InventoryRollbackPlus] Plugin InventoryRollbackPlus v1.6.8 generated an exception while executing task 4786263
java.lang.IllegalStateException: Unable to save item stacks.
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:154) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at me.danjono.inventoryrollback.data.MySQL.setMainInventory(MySQL.java:236) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at me.danjono.inventoryrollback.data.PlayerData.setMainInventory(PlayerData.java:147) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.lambda$createSave$1(SaveInventory.java:96) ~[[I][背包备 份]InventoryRollbackPlus-1.6.8.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: swallow=2 and swallow=2
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1515) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1435) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1411) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1157) ~[?:?]
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1391) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191) ~[?:?]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354) ~[?:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:148) ~[[I][背包备份]InventoryRollbackPlus-1.6.8.jar:?]
        ... 9 more
#### **Additional info:**
I'm very sorry, because I'm from China, so my English is machine translation. I hope you can understand it. I really need your help. If I solve it, I will sponsor you.
![EW X982C L@MPL$E1$~D3QU](https://user-images.githubusercontent.com/118680442/226199040-e928c870-689b-4f2a-b8c2-b81bb1bebab7.png)
![R1ZANJDO8~FS$ME@FLH$C V](https://user-images.githubusercontent.com/118680442/226199048-2bb60a68-9242-4c0f-85b9-3dd3dca0a35e.png)

**Comment by TechnicallyCoded** [comment]
Are you using custom enchantments?

**Comment by TechnicallyCoded** [comment]
No reply
