### ISSUE TITLE
When I join and leave I see this errors in the console 

### ISSUE THREAD

**Issue by ICookBacon123** [TechnicallyCoded/Inventory-Rollback-Plus#128]
*Ask your question here*
[11:31:27 WARN]: java.sql.SQLNonTransientConnectionException: SSL Connection required, but not provided by server.
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:79)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
[11:31:27 WARN]: at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[11:31:27 WARN]: at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
[11:31:27 WARN]: at InventoryRollbackPlus-1.6.9.jar//me.danjono.inventoryrollback.data.MySQL.openConnection(MySQL.java:79)
[11:31:27 WARN]: at InventoryRollbackPlus-1.6.9.jar//me.danjono.inventoryrollback.data.MySQL.getAmountOfBackups(MySQL.java:171)
[11:31:27 WARN]: at InventoryRollbackPlus-1.6.9.jar//me.danjono.inventoryrollback.data.PlayerData.getAmountOfBackups(PlayerData.java:86)
[11:31:27 WARN]: at InventoryRollbackPlus-1.6.9.jar//me.danjono.inventoryrollback.data.PlayerData.lambda$purgeExcessSaves$0(PlayerData.java:118)
[11:31:27 WARN]: at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[11:31:27 WARN]: at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:31:27 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:31:27 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:31:27 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:31:27 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[11:31:27 WARN]: Caused by: com.mysql.cj.exceptions.UnableToConnectException: SSL Connection required, but not provided by server.
[11:31:27 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:31:27 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[11:31:27 WARN]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:31:27 WARN]: at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[11:31:27 WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[11:31:27 WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[11:31:27 WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[11:31:27 WARN]: at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:147)
[11:31:27 WARN]: at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1429)
[11:31:27 WARN]: at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:944)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:814)
[11:31:27 WARN]: ... 15 more
[11:31:27 WARN]: java.sql.SQLNonTransientConnectionException: SSL Connection required, but not provided by server.
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[11:31:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:79)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
[11:31:27 WARN]: at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[11:31:27 WARN]: at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
[11:31:27 WARN]: at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
[11:31:27 WARN]: at InventoryRollbackPlus-1.6.9.jar//me.danjono.inventoryrollback.data.MySQL.openConnection(MySQL.java:79)
[11:31:27 WARN]: at InventoryRollbackPlus-1.6.9.jar//me.danjono.inventoryrollback.data.MySQL.saveData(MySQL.java:403)
[11:31:27 WARN]: at InventoryRollbackPlus-1.6.9.jar//me.danjono.inventoryrollback.data.PlayerData.lambda$saveData$1(PlayerData.java:433)
[11:31:27 WARN]: at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[11:31:27 WARN]: at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:31:27 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:31:27 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:31:27 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:31:27 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[11:31:27 WARN]: Caused by: com.mysql.cj.exceptions.UnableToConnectException: SSL Connection required, but not provided by server.
[11:31:27 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:31:27 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[11:31:27 WARN]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:31:27 WARN]: at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[11:31:27 WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[11:31:27 WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[11:31:27 WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[11:31:27 WARN]: at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:147)
[11:31:27 WARN]: at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1429)
[11:31:27 WARN]: at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:944)
[11:31:27 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:814)
[11:31:27 WARN]: ... 14 more

**Comment by TechnicallyCoded** [comment]
"SSL Connection required, but not provided by server."
Disable SSL in the configuration file.
