### ISSUE TITLE
Error on many events

### ISSUE THREAD

**Issue by john-whiting** [TechnicallyCoded/Inventory-Rollback-Plus#14]
Hello, I got this error when using SSSpigot for 1.16 and trying to use Inventory-Rollback-Plus.

```
[00:11:12 ERROR]: Could not pass event EntityDamageEvent to InventoryRollbackPlus v1.6.0
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/mysql/cj/protocol/ExportControlled.encryptWithRSAPublicKey([BLjava/security/interfaces/RSAPublicKey;Ljava/lang/String;)[B @21: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[1]) is not assignable to 'java/security/GeneralSecurityException'
  Current Frame:
    bci: @21
    flags: { }
    locals: { top, top, top, 'java/lang/Object' }
    stack: { 'java/lang/Class', 'java/lang/Object' }
  Bytecode:
    0000000: 2cb8 00ce 594e 042b b600 cf2d 2ab6 00cd
    0000010: b04e 123b 2db6 00ba 2db8 008b c000 3bbf
    0000020:                                        
  Exception Handler Table:
    bci [0, 16] => handler: 17
    bci [0, 16] => handler: 17
    bci [0, 16] => handler: 17
    bci [0, 16] => handler: 17
    bci [0, 16] => handler: 17
  Stackmap Table:
    full_frame(@17,{},{Object[#73]})

        at com.mysql.cj.protocol.NetworkResources.forceClose(NetworkResources.java:53) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at com.mysql.cj.protocol.AbstractSocketConnection.forceClose(AbstractSocketConnection.java:103) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1235) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at com.mysql.cj.NativeSession.quit(NativeSession.java:174) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1738) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:718) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at me.danjono.inventoryrollback.data.MySQL.closeConnection(MySQL.java:97) ~[?:?]
        at me.danjono.inventoryrollback.data.MySQL.getAmountOfBackups(MySQL.java:184) ~[?:?]
        at me.danjono.inventoryrollback.data.PlayerData.getAmountOfBackups(PlayerData.java:83) ~[?:?]
        at me.danjono.inventoryrollback.data.PlayerData.purgeExcessSaves(PlayerData.java:110) ~[?:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.createSave(SaveInventory.java:43) ~[?:?]
        at me.danjono.inventoryrollback.listeners.EventLogs.playerDeath(EventLogs.java:49) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:622) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:253) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1089) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1071) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:932) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1121) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:2126) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:965) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1353) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:882) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:1149) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.EntityLiving.b(EntityLiving.java:1942) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.EntityHuman.b(EntityHuman.java:1643) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.Block.fallOn(Block.java:320) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.Entity.a(Entity.java:1594) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.EntityLiving.a(EntityLiving.java:345) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.EntityPlayer.a(EntityPlayer.java:1614) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1512) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:53) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:108) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1342) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1335) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1428) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[ssspigot2426142275705628855.jar:SSSpigot2-1.16.5-20210429-05e1bec]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by TechnicallyCoded** [comment]
As replied using the spigot discussion thread. This doesn't seem to be related to Inventory Rollback itself. Please try running IRP on spigot, paper, tuinity, or purpur and see if the same issue occurs.
