### ISSUE TITLE
Irp restore

### ISSUE THREAD

**Issue by Valpyx** [TechnicallyCoded/Inventory-Rollback-Plus#148]
On version 1.20.1 plugin works good, but when i try on 1.20.4 /irp restore i have a problem

[13:06:14 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[13:06:14 WARN]: at java.base/java.lang.Class.getMethod(Class.java:2259)
[13:06:14 WARN]: at InventoryRollbackPlus-1.6.12.jar//me.danjono.inventoryrollback.reflections.NBTWrapper.getString(NBTWrapper.java:194)
[13:06:14 WARN]: at InventoryRollbackPlus-1.6.12.jar//me.danjono.inventoryrollback.reflections.NBTWrapper.hasUUID(NBTWrapper.java:83)
[13:06:14 WARN]: at InventoryRollbackPlus-1.6.12.jar//me.danjono.inventoryrollback.listeners.ClickGUI.mainMenu(ClickGUI.java:126)
[13:06:14 WARN]: at InventoryRollbackPlus-1.6.12.jar//me.danjono.inventoryrollback.listeners.ClickGUI.onInventoryClick(ClickGUI.java:95)
[13:06:14 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor473.execute(Unknown Source)

**Comment by Bossbirdyman51** [comment]
+1

**Comment by TechnicallyCoded** [comment]
Update the plugin please. You automatically get update notifications in console.
