### ISSUE TITLE
Support:  Unable to save item stacks.

### ISSUE THREAD

**Issue by borekKSH** [TechnicallyCoded/Inventory-Rollback-Plus#159]
[19:57:33 WARN]: [InventoryRollbackPlus] Plugin InventoryRollbackPlus v1.6.17 generated an exception while executing task 325264
java.lang.IllegalStateException: Unable to save item stacks.
	at InventoryRollbackPlus-1.6.17.jar/me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:173) ~[InventoryRollbackPlus-1.6.17.jar:?]
	at InventoryRollbackPlus-1.6.17.jar/me.danjono.inventoryrollback.data.MySQL.setEnderChest(MySQL.java:244) ~[InventoryRollbackPlus-1.6.17.jar:?]
	at InventoryRollbackPlus-1.6.17.jar/me.danjono.inventoryrollback.data.PlayerData.setEnderChest(PlayerData.java:163) ~[InventoryRollbackPlus-1.6.17.jar:?]
	at InventoryRollbackPlus-1.6.17.jar/me.danjono.inventoryrollback.inventory.SaveInventory.lambda$createSave$1(SaveInventory.java:117) ~[InventoryRollbackPlus-1.6.17.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-50-20889d0]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-50-20889d0]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: null value in entry: using-converts-to=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:54) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:341) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:450) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:465) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:494) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:477) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1160) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1394) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1190) ~[?:?]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1585) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1542) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194) ~[?:?]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1585) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1542) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1394) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1190) ~[?:?]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1585) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1542) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194) ~[?:?]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1585) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1542) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358) ~[?:?]
	at InventoryRollbackPlus-1.6.17.jar/me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:167) ~[InventoryRollbackPlus-1.6.17.jar:?]
	... 9 more   IT is normal?

**Comment by TechnicallyCoded** [comment]
Which item?

**Comment by TechnicallyCoded** [comment]
I need that information please or I can't fix it

**Comment by TechnicallyCoded** [comment]
The player's data file please. Based on their UUID.

**Comment by TechnicallyCoded** [comment]
Yes that's the folder

**Comment by TechnicallyCoded** [comment]
Ya, except I need to know who it was... That's the data of every player, I just need the problematic one

**Comment by TechnicallyCoded** [comment]
Ok I can reproduce your problem using the player data file you sent. Now I need to find why.

**Comment by TechnicallyCoded** [comment]
I forwarded the bug over to spigot since it has to do with handling items in general and no with the plugin specifically. I'll let you know if/when I get a reply.

**Comment by TechnicallyCoded** [comment]
Update: the issue was supposedly fixed in spigot (I'll be checking that). We now still need to wait for Paper to update from upstream for this to be correctly resolved.

**Comment by BadAreBones** [comment]
I have the same issue!  Please fix ASAP

**Comment by BadAreBones** [comment]
I'm having the same issue!  Please try and fix it it broke the plugin and spams console :(

**Comment by TechnicallyCoded** [comment]
Please try and read the above issue before posting. Not an issue with the plugin, not fixable on my part. 
You can also provide additional information such as the your server version (screenshot /version) and IRP version (/irp version) such as to make helping you possible..

**Comment by TechnicallyCoded** [comment]
@borekKSH Has this issue been resolved in newer versions? If so, we can close this.

**Comment by TechnicallyCoded** [comment]
No reply
