### ISSUE TITLE
Bug report: java.lang.NoSuchMethodException (Paper 1.21.1)

### ISSUE THREAD

**Issue by shiny-spark** [TechnicallyCoded/Inventory-Rollback-Plus#164]
### Bug description:
*After opening menu with /irp restore then clicking on any button, nothing happens*

### Server details:
 - Paper version 1.21.1-10-master@098bd39 (2024-08-11T22:37:37Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)*
 - InventoryRollbackPlus v1.6.17*

### How to reproduce:
*write /ir restore <username> in chat*

### What was expected:
*I can restore backup.*

### Screenshots, logs & other:
```
[09:23:19 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[09:23:19 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2395)
[09:23:19 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getMethod(AbstractDefaultRulesReflectionProxy.java:100)
[09:23:19 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getMethod(Unknown Source)
[09:23:19 WARN]:        at InventoryRollbackPlus-1.6.17.jar//me.danjono.inventoryrollback.reflections.NBTWrapper.readNbtFromNmsItem(NBTWrapper.java:217)
[09:23:19 WARN]:        at InventoryRollbackPlus-1.6.17.jar//me.danjono.inventoryrollback.reflections.NBTWrapper.readDataFromBukkitItem(NBTWrapper.java:194)
[09:23:19 WARN]:        at InventoryRollbackPlus-1.6.17.jar//me.danjono.inventoryrollback.reflections.NBTWrapper.getString(NBTWrapper.java:164)
[09:23:19 WARN]:        at InventoryRollbackPlus-1.6.17.jar//me.danjono.inventoryrollback.reflections.NBTWrapper.hasUUID(NBTWrapper.java:138)
[09:23:19 WARN]:        at InventoryRollbackPlus-1.6.17.jar//me.danjono.inventoryrollback.listeners.ClickGUI.playerMenu(ClickGUI.java:161)
[09:23:19 WARN]:        at InventoryRollbackPlus-1.6.17.jar//me.danjono.inventoryrollback.listeners.ClickGUI.onInventoryClick(ClickGUI.java:100)
[09:23:19 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor471.execute(Unknown Source)
[09:23:19 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[09:23:19 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[09:23:19 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:23:19 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[09:23:19 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[09:23:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[09:23:19 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3117)
[09:23:19 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[09:23:19 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[09:23:19 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[09:23:19 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:23:19 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[09:23:19 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[09:23:19 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[09:23:19 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[09:23:19 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[09:23:19 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[09:23:19 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[09:23:19 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[09:23:19 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)
[09:23:19 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473)
[09:23:19 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318)
[09:23:19 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[09:23:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

#### **Additional info:**
*N/A*

**Comment by TechnicallyCoded** [comment]
Fixed in b5019c175b1264a38a6a759836b048fb985db804 (1.6.18)
