### ISSUE TITLE
Bug report: [Back Ups Aren't Saving]

### ISSUE THREAD

**Issue by nicholasveronico** [TechnicallyCoded/Inventory-Rollback-Plus#27]
### Bug description:
Whenever a player joins, quits, etc. or when I try to force save a player, I get the following error:
```
[11:33:00 WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'ender_chest' at row 1
[11:33:00 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
[11:33:00 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[11:33:00 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[11:33:00 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[11:33:00 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[11:33:00 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[11:33:00 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
[11:33:00 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
[11:33:00 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
[11:33:00 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
[11:33:00 WARN]:        at me.danjono.inventoryrollback.data.MySQL.saveData(MySQL.java:425)
[11:33:00 WARN]:        at me.danjono.inventoryrollback.data.PlayerData.lambda$saveData$0(PlayerData.java:407)
[11:33:00 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[11:33:00 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[11:33:00 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:33:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[11:33:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[11:33:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

### Server details:
 - Server type & version: SSSpigot version SSSpigot2-1.16.5-20210523-ffabb18 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - InventoryRollbackPlus version: v1.6.1

### How to reproduce:
A player having an ender chest filled with all shulkers, which causes a sql error in the console whenever they leave, join, die or they are force saved.

### What was expected:
I expect there not to be a sql error and for the inventories, as well as the ender chests to be saved when the player leaves, joins, dies, or is force saved.

### Screenshots, logs & other:
https://pastebin.com/BjJHj4Fd

#### **Additional info:**
N/A

**Comment by TechnicallyCoded** [comment]
Can you log into your database and send me the table structure that you are currently using for the rollbacks?

**Comment by nicholasveronico** [comment]
> Can you log into your database and send me the table structure that you are currently using for the rollbacks?

Is this what you mean?
![Capture](https://user-images.githubusercontent.com/80995156/126041888-8bdedbb0-1bfb-48a1-a228-e62bd17ce331.PNG)

**Comment by TechnicallyCoded** [comment]
Yes, that but the structure of one of the tables. Like for example, backup_deaths. Then click on this tab and show me what you see there. 
![image](https://user-images.githubusercontent.com/29813490/126043409-9c30f29f-09f8-4115-b76a-3a1a936471d2.png)

**Comment by nicholasveronico** [comment]
> Yes, that is almost it. I need the structure of one of the tables. Like for example, backup_deaths. Once viewing the table, click on this tab and show me what you see there.
> ![image](https://user-images.githubusercontent.com/29813490/126043409-9c30f29f-09f8-4115-b76a-3a1a936471d2.png)

Oh my bad. Here's all of them:
Force Backups
![backup_force_backups](https://user-images.githubusercontent.com/80995156/126051018-9387b795-320b-4b3a-a4ac-07e8a14c03ac.PNG)
Joins
![backup_joins](https://user-images.githubusercontent.com/80995156/126051019-365fde60-752d-41cb-96fe-db7b280a6068.PNG)
Quits
![backup_quits](https://user-images.githubusercontent.com/80995156/126051020-2e1d2f48-0379-471d-a7ec-ba80e2b6f73b.PNG)
World Changes
![backup_world_changes](https://user-images.githubusercontent.com/80995156/126051021-4379bbc7-3848-4557-ade1-927fbb9ebc58.PNG)
Deaths
![backup_deaths](https://user-images.githubusercontent.com/80995156/126051022-57334135-23a0-41ea-8fd9-160ed8202791.PNG)

**Comment by TechnicallyCoded** [comment]
Yes, this is what I guessed hence why I asked for the table structure: you have been using the plugin since before the latest update which fixed this potential issue. The inventory saves now use LONGTEXT instead of TEXT when creating a table. (reference commit: [https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/commit/e65f1e2181e25e28203938e597fc4dfa67eef1ca](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/commit/e65f1e2181e25e28203938e597fc4dfa67eef1ca)).

If you know how to modify table structures you can switch them over. Otherwise, makes sure you have a backup of all important data and you can delete the tables for the IRP plugin. Upon creation you should see that the main_inv, armour, ender_chest, etc.. are now LONGTEXT.

**Comment by nicholasveronico** [comment]
> Yes, this is what I guessed hence why I asked for the table structure: you have been using the plugin since before the latest update which fixed this potential issue. The inventory saves now use LONGTEXT instead of TEXT when creating a table. (reference commit: [e65f1e2](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/commit/e65f1e2181e25e28203938e597fc4dfa67eef1ca)).
> 
> If you know how to modify table structures you can switch them over. Otherwise, makes sure you have a backup of all important data and you can delete the tables for the IRP plugin. Upon creation you should see that the main_inv, armour, ender_chest, etc.. are now LONGTEXT.

Alright I have altered the tables and I think that fixed it. I should also mention that my back ups still save with the GMT timezone when I have it set to EST in the config. Any idea why?

**Comment by TechnicallyCoded** [comment]
All backups should save using universal unix timestamps. However, when displaying the time to the user, it should translate that. Make sure there is no mention of defaulting back to GMT in your log file. (Search for GMT in latest.log)

**Comment by nicholasveronico** [comment]
Getting this in the logs:

[07:59:43] [Server thread/WARN]: [InventoryRollbackPlus] Time zone ID "EST" in config.yml is not valid. Defaulting to "GMT"

**Comment by srnyx** [comment]
> Didn't realize it was GMT+/-# for the timezone

I think this should be made more clear. @TechnicallyCoded
