### ISSUE TITLE
Support: Setting up MySQL database

### ISSUE THREAD

**Issue by 1van0** [TechnicallyCoded/Inventory-Rollback-Plus#58]
Hey,

First of all, I love your plugin.
but I had some issues setting up a MySQL database.
So when I fill in my details of my MySQL database and restart my server, I get this error in the console?.

`[01.01 19:25:26] [Server] [WARN] com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[01.01 19:25:26] [Server] [WARN] 
[01.01 19:25:26] [Server] [WARN] The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[01.01 19:25:26] [Server] [WARN] 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
[01.01 19:25:26] [Server] [WARN] 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
[01.01 19:25:26] [Server] [WARN] 	at InventoryRollbackPlus-1.6.5.jar//me.danjono.inventoryrollback.data.MySQL.openConnection(MySQL.java:78)
[01.01 19:25:26] [Server] [WARN] 	at InventoryRollbackPlus-1.6.5.jar//me.danjono.inventoryrollback.data.MySQL.createTables(MySQL.java:101)
[01.01 19:25:26] [Server] [WARN] 	at InventoryRollbackPlus-1.6.5.jar//me.danjono.inventoryrollback.InventoryRollback.startupTasks(InventoryRollback.java:96)
[01.01 19:25:26] [Server] [WARN] 	at InventoryRollbackPlus-1.6.5.jar//com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus.onEnable(InventoryRollbackPlus.java:57)
[01.01 19:25:26] [Server] [WARN] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01.01 19:25:26] [Server] [WARN] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01.01 19:25:26] [Server] [WARN] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[01.01 19:25:26] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[01.01 19:25:26] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[01.01 19:25:26] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730)
[01.01 19:25:26] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506)
[01.01 19:25:26] [Server] [WARN] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:347)
[01.01 19:25:26] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1215)
[01.01 19:25:26] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[01.01 19:25:26] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)
[01.01 19:25:26] [Server] [WARN] Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[01.01 19:25:26] [Server] [WARN] 
[01.01 19:25:26] [Server] [WARN] The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[01.01 19:25:26] [Server] [WARN] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01.01 19:25:26] [Server] [WARN] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[01.01 19:25:26] [Server] [WARN] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01.01 19:25:26] [Server] [WARN] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[01.01 19:25:26] [Server] [WARN] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:317)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:203)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1369)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
[01.01 19:25:26] [Server] [WARN] 	... 20 more
[01.01 19:25:26] [Server] [WARN] Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:335)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:194)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:101)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:308)
[01.01 19:25:26] [Server] [WARN] 	... 25 more
[01.01 19:25:26] [Server] [WARN] Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.protocol.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:404)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
[01.01 19:25:26] [Server] [WARN] 	... 40 more
[01.01 19:25:26] [Server] [WARN] Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:157)
[01.01 19:25:26] [Server] [WARN] 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
[01.01 19:25:26] [Server] [WARN] 	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
[01.01 19:25:26] [Server] [WARN] 	at com.mysql.cj.protocol.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:398)
[01.01 19:25:26] [Server] [WARN] 	... 42 more`

It has a weird link failure. I made sure I filled in all of my details correctly.
Also, I don't know if this is a problem whit the mod or the database.
But Luckperms works on my database?

anyways hope you can help me.

cheers, Ivan

**Comment by TechnicallyCoded** [comment]
The real error in all this mess is: `javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors`

It's probably due to you using SSL for a database that doesn't have a verified SSL certificate. If you are running the database locally (such as 127.0.0.1 or 178.18.0.1 or localhost, you can just disable certificate verification or SSL altogether since someone would need access to the machine itself to sniff the data going by). If not on localhost, you will need to see what's going on with the database host. It's usually indicative of a self-signed ssl cert which is not a whole lot better than no SSL at all (it is technically better but can easily be spoofed/manipulated).

Also, please use a multi-line code block next time as it makes it much easier to read the errors.

**Comment by 1van0** [comment]
Thank you. I fixed the error by setting the `use-SSL` value to false. also sorry for pasting the whole error in the wrong format.
