### ISSUE TITLE
Inventory rollback mmoitems support (feature request)

### ISSUE THREAD

**Issue by dinobossytnew** [TechnicallyCoded/Inventory-Rollback-Plus#7]
https://pastebin.com/DpD5C224

1.16.4

**Comment by dinobossytnew** [comment]
[03:58:33 ERROR]: Could not pass event EntityDamageByEntityEvent to InventoryRollbackPlus v1.6.0
java.lang.IllegalStateException: Unable to save item stacks.
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:115) ~[?:?]
        at me.danjono.inventoryrollback.data.YAML.setMainInventory(YAML.java:187) ~[?:?]
        at me.danjono.inventoryrollback.data.PlayerData.setMainInventory(PlayerData.java:129) ~[?:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.createSave(SaveInventory.java:47) ~[?:?]
        at me.danjono.inventoryrollback.listeners.EventLogs.playerDeathByEntity(EventLogs.java:63) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor87.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-393]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:244) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1038) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:925) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:881) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1070) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1830) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1165) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:844) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityIronGolem.attackEntity(EntityIronGolem.java:149) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.a(SourceFile:142) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.e(SourceFile:134) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:153) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityInsentient.doTick(EntityInsentient.java:760) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.movementTick(EntityLiving.java:2764) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityInsentient.movementTick(EntityInsentient.java:546) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityIronGolem.movementTick(EntityIronGolem.java:69) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2489) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:309) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.World.a(World.java:886) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: §9Cubism=3 and §9Cubism=5
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1481) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1400) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1376) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48) ~[patched_1.16.4.jar:git-Paper-393]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1145) ~[?:?]
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1379) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[?:?]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[?:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:110) ~[?:?]
        ... 39 more
[03:58:33 ERROR]: Could not pass event PlayerDeathEvent to StaffPlus v3.3.5.0
java.lang.IllegalArgumentException: Multiple entries with same key: §9Cubism=3 and §9Cubism=5
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1481) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1400) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1376) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:39) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:41) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:27) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:275) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243) ~[patched_1.16.4.jar:git-Paper-393]
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:220) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:41) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[patched_1.16.4.jar:git-Paper-393]
        at net.shortninja.staffplus.player.attribute.InventorySerializer.save(InventorySerializer.java:112) ~[?:?]
        at net.shortninja.staffplus.player.attribute.mode.ModeDataVault.<init>(ModeDataVault.java:68) ~[?:?]
        at net.shortninja.staffplus.player.attribute.mode.handler.ReviveHandler.cacheInventory(ReviveHandler.java:32) ~[?:?]
        at net.shortninja.staffplus.server.listener.player.PlayerDeath.onDeath(PlayerDeath.java:21) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor180.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-393]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:823) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:675) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1267) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:844) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityIronGolem.attackEntity(EntityIronGolem.java:149) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.a(SourceFile:142) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.e(SourceFile:134) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:153) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityInsentient.doTick(EntityInsentient.java:760) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.movementTick(EntityLiving.java:2764) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityInsentient.movementTick(EntityInsentient.java:546) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityIronGolem.movementTick(EntityIronGolem.java:69) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2489) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:309) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.World.a(World.java:886) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[03:58:33 ERROR]: Could not pass event PlayerDeathEvent to AngelChest v2.22.1
java.lang.IllegalArgumentException: Multiple entries with same key: §9Cubism=3 and §9Cubism=5
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1481) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1400) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1376) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.toString(CraftMetaItem.java:1548) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.String.valueOf(String.java:2951) ~[?:?]
        at java.lang.StringBuilder.append(StringBuilder.java:168) ~[?:?]
        at org.bukkit.inventory.ItemStack.toString(ItemStack.java:258) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.String.valueOf(String.java:2951) ~[?:?]
        at java.lang.StringBuilder.append(StringBuilder.java:168) ~[?:?]
        at de.jeff_media.AngelChest.AngelChest.<init>(AngelChest.java:170) ~[?:?]
        at de.jeff_media.AngelChest.PlayerListener.spawnAngelChest(PlayerListener.java:204) ~[?:?]
        at de.jeff_media.AngelChest.PlayerListener.spawnAngelChestNormal(PlayerListener.java:71) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor749.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-393]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:823) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:675) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1267) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:844) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityIronGolem.attackEntity(EntityIronGolem.java:149) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.a(SourceFile:142) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.e(SourceFile:134) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:153) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityInsentient.doTick(EntityInsentient.java:760) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.movementTick(EntityLiving.java:2764) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityInsentient.movementTick(EntityInsentient.java:546) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityIronGolem.movementTick(EntityIronGolem.java:69) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2489) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:309) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.World.a(World.java:886) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[03:58:33 INFO]: Rimuru_TempestYT was slain by Iron Golem
[03:58:36 ERROR]: Could not pass event PlayerChangedWorldEvent to InventoryRollbackPlus v1.6.0
java.lang.IllegalStateException: Unable to save item stacks.
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:115) ~[?:?]
        at me.danjono.inventoryrollback.data.YAML.setMainInventory(YAML.java:187) ~[?:?]
        at me.danjono.inventoryrollback.data.PlayerData.setMainInventory(PlayerData.java:129) ~[?:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.createSave(SaveInventory.java:47) ~[?:?]
        at me.danjono.inventoryrollback.listeners.EventLogs.playerChangeWorld(EventLogs.java:75) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Paper-393]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:894) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:719) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2296) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PacketPlayInClientCommand.a(SourceFile:30) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1082) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-393]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: §9Cubism=3 and §9Cubism=5
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88) ~[patched_1.16.4.jar:git-Paper-393]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1481) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1400) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1376) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16) ~[patched_1.16.4.jar:git-Paper-393]
        at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48) ~[patched_1.16.4.jar:git-Paper-393]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1145) ~[?:?]
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1379) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[?:?]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553) ~[?:?]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510) ~[?:?]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[?:?]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[?:?]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[?:?]
        at me.danjono.inventoryrollback.inventory.SaveInventory.toBase64(SaveInventory.java:110) ~[?:?]
        ... 25 more

**Comment by dinobossytnew** [comment]
> Este problema parece no estar relacionado con este complemento específico.
> 
> Parece que tiene artículos no válidos en su inventario. Es aún más obvio por el hecho de que muchos otros complementos también se bloquean en los registros que proporcionó.
> 
> No sé de qué es esto (a continuación), pero se parece mucho a los elementos personalizados que creó.
> `§9Cubism=3 and §9Cubism=5`

mmoitems 
plis add suport?

**Comment by TechnicallyCoded** [comment]
I never used mmoitems but if the item is "bukkit serializable" it should work by default since I am just using bukkit's built in system to transform the items into text. I cannot be 100% sure about this but it seems to me like mmoitems needs to add support for item serialization rather than each plugin having to write custom adapters to fix the problem they created.

If you know of any other plugin that does support this item format that I could take a look at to know how to implement support please link that here.

**Comment by TechnicallyCoded** [comment]
Issue will be closed in a week if no additional information is provided.

**Comment by TechnicallyCoded** [comment]
No info was provided for about a month. Feature request closed.
