### ISSUE TITLE
Bug report: 1.18.2 Support

### ISSUE THREAD

**Issue by Thijsvl12** [TechnicallyCoded/Inventory-Rollback-Plus#73]
### Bug description:
After opening menu with /irp restore <player name> then clicking on any button, nothing happens

### Server details:
 - Server type & version: Paper version git-Paper-220 (MC: 1.18.2)
 - InventoryRollbackPlus version: v1.6.5

### How to reproduce:
N/A

### What was expected:
I can restore backup.

### Screenshots, logs & other:
```
[12:35:10 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[12:35:10 WARN]:        at java.base/java.lang.Class.getMethod(Unknown Source)
[12:35:10 WARN]:        at InventoryRollbackPlus-1.6.5.jar//me.danjono.inventoryrollback.reflections.NBTWrapper.setString(NBTWrapper.java:74)
[12:35:10 WARN]:        at InventoryRollbackPlus-1.6.5.jar//me.danjono.inventoryrollback.gui.Buttons.createForceSaveLogButton(Buttons.java:459)
[12:35:10 WARN]:        at InventoryRollbackPlus-1.6.5.jar//me.danjono.inventoryrollback.gui.menu.PlayerMenu.getPlayerMenu(PlayerMenu.java:100)
[12:35:10 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[12:35:10 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:35:10 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:35:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:35:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:35:10 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```

#### **Additional info:**
N/A

**Comment by TechnicallyCoded** [comment]
1.18.2 is not supported yet, I am not home for the week due to vacation. The plugin will be updated once I am back (in a few days) with a few additional features that I have been testiing privately with some servers.

**Comment by DJLost12** [comment]
No worries technically. The work you've put in keeping this particular feature rolling for us that rely on it is appreciated. We'll survive. thank you for your work here man.

**Comment by Captainpax** [comment]
have the same problem.

**Comment by TechnicallyCoded** [comment]
Currently working on it, should be out real soon :)

**Comment by TechnicallyCoded** [comment]
To everyone here, this issue should be resolved!
