### ISSUE TITLE
NoSuchFieldError 

### ISSUE THREAD

**Issue by Rbot48** [TechnicallyCoded/Inventory-Rollback-Plus#8]
Hey,
I am getting a NoSuchFieldError when running the plugin on Paper 1.10.2:

```
[24.03 16:01:13] [Server] [ERROR] Could not pass event EntityDamageEvent to InventoryRollbackPlus v1.6.0
[24.03 16:01:13] [Server] org.bukkit.event.EventException
[24.03 16:01:13] [Server] 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:558) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:868) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:793) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:516) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.EntityLiving.e(EntityLiving.java:1123) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.EntityHuman.e(EntityHuman.java:1557) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.Block.fallOn(Block.java:537) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.Entity.a(Entity.java:935) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.EntityLiving.a(EntityLiving.java:176) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.EntityPlayer.a(EntityPlayer.java:693) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:643) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_271]
[24.03 16:01:13] [Server] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_271]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
[24.03 16:01:13] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
[24.03 16:01:13] [Server] Caused byjava.lang.NoSuchFieldError: ENTITY_SWEEP_ATTACK
[24.03 16:01:13] [Server] 	at me.danjono.inventoryrollback.listeners.EventLogs.isEntityCause(EventLogs.java:83) ~[InventoryRollbackPlus-1.6.0.jar:?]
[24.03 16:01:13] [Server] 	at me.danjono.inventoryrollback.listeners.EventLogs.playerDeath(EventLogs.java:44) ~[InventoryRollbackPlus-1.6.0.jar:?]
[24.03 16:01:13] [Server] 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.10.2.jar:git-Paper-916.2]
```

**Comment by TechnicallyCoded** [comment]
Does this always happen in 1.10? Or are there specific cases where it does?
Only mobs? Only players?

Please help me with more context :), in the meantime, I will dig through the code and see if I can track this down!

**Comment by Rbot48** [comment]
Hey,
I was not able to reproduce the above error when fighting with another player or mob, but it shows up from time to time.
However, a similar stacktrace is shown when a player is damaged

By fire:
```
Could not pass event EntityDamageEvent to InventoryRollbackPlus v1.6.0
org.bukkit.event.EventException
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.10.2.jar:git-Paper-916.2]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:558) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:868) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:793) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:516) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.Entity.U(Entity.java:392) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityLiving.U(EntityLiving.java:185) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.Entity.m(Entity.java:321) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1768) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityHuman.m(EntityHuman.java:157) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:258) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:139) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:152) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:903) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NoSuchFieldError: ENTITY_SWEEP_ATTACK
        at me.danjono.inventoryrollback.listeners.EventLogs.isEntityCause(EventLogs.java:83) ~[InventoryRollbackPlus-1.6.0.jar:?]
        at me.danjono.inventoryrollback.listeners.EventLogs.playerDeath(EventLogs.java:44) ~[InventoryRollbackPlus-1.6.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.10.2.jar:git-Paper-916.2]
        ... 27 more
```

By falling:
```
Could not pass event EntityDamageEvent to InventoryRollbackPlus v1.6.0
org.bukkit.event.EventException
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.10.2.jar:git-Paper-916.2]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:558) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1258) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:868) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:850) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:793) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:516) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityLiving.e(EntityLiving.java:1123) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityHuman.e(EntityHuman.java:1557) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.Block.fallOn(Block.java:537) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.Entity.a(Entity.java:935) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityLiving.a(EntityLiving.java:176) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.EntityPlayer.a(EntityPlayer.java:693) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:643) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-916.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_221]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NoSuchFieldError: ENTITY_SWEEP_ATTACK
        at me.danjono.inventoryrollback.listeners.EventLogs.isEntityCause(EventLogs.java:83) ~[InventoryRollbackPlus-1.6.0.jar:?]
        at me.danjono.inventoryrollback.listeners.EventLogs.playerDeath(EventLogs.java:44) ~[InventoryRollbackPlus-1.6.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.10.2.jar:git-Paper-916.2]
        ... 31 more
```

**Comment by TechnicallyCoded** [comment]
I just realized I never answered you about this. Sorry. This will be fixed in the following version. However I do recommend you update to 1.16 since that is the best supported version.
