### ISSUE TITLE
MYSQL Error

### ISSUE THREAD

**Issue by 05Arana** [TechnicallyCoded/Inventory-Rollback-Plus#80]
Hi, when i try to connect my config.yml with phpmyadmin and i reload the pluguin i have this error: 

[02:22:08 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[02:22:08 WARN]:
[02:22:08 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[02:22:08 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[02:22:08 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[02:22:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[02:22:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
[02:22:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[02:22:08 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[02:22:08 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
[02:22:08 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
[02:22:08 WARN]:        at InventoryRollbackPlus-1.6.6.jar//me.danjono.inventoryrollback.data.MySQL.openConnection(MySQL.java:78)
[02:22:08 WARN]:        at InventoryRollbackPlus-1.6.6.jar//me.danjono.inventoryrollback.data.MySQL.createTables(MySQL.java:101)
[02:22:08 WARN]:        at InventoryRollbackPlus-1.6.6.jar//me.danjono.inventoryrollback.InventoryRollback.startupTasks(InventoryRollback.java:96)
[02:22:08 WARN]:        at InventoryRollbackPlus-1.6.6.jar//com.nuclyon.technicallycoded.inventoryrollback.commands.inventoryrollback.ReloadSubCmd.onCommand(ReloadSubCmd.java:18)
[02:22:08 WARN]:        at InventoryRollbackPlus-1.6.6.jar//com.nuclyon.technicallycoded.inventoryrollback.commands.Commands.onCommand(Commands.java:49)
[02:22:08 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:22:08 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[02:22:08 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:908)
[02:22:08 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:871)
[02:22:08 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:507)
[02:22:08 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
[02:22:08 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[02:22:08 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1273)
[02:22:08 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[02:22:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:22:08 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[02:22:08 WARN]:
[02:22:08 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[02:22:08 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor156.newInstance(Unknown Source)
[02:22:08 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[02:22:08 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[02:22:08 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[02:22:08 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[02:22:08 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[02:22:08 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[02:22:08 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[02:22:08 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:317)
[02:22:08 WARN]:        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:203)
[02:22:08 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1369)
[02:22:08 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
[02:22:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
[02:22:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
[02:22:08 WARN]:        ... 20 more
[02:22:08 WARN]: Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
[02:22:08 WARN]:        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[02:22:08 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
[02:22:08 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
[02:22:08 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
[02:22:08 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
[02:22:08 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
[02:22:08 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
[02:22:08 WARN]:        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[02:22:08 WARN]:        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[02:22:08 WARN]:        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[02:22:08 WARN]:        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
[02:22:08 WARN]:        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[02:22:08 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
[02:22:08 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
[02:22:08 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
[02:22:08 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
[02:22:08 WARN]:        at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:335)
[02:22:08 WARN]:        at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:194)
[02:22:08 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:101)
[02:22:08 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:308)
[02:22:08 WARN]:        ... 25 more
[02:22:08 WARN]: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
[02:22:08 WARN]:        at com.mysql.cj.protocol.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:404)
[02:22:08 WARN]:        at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)
[02:22:08 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
[02:22:08 WARN]:        ... 40 more
[02:22:08 WARN]: Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
[02:22:08 WARN]:        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:157)
[02:22:08 WARN]:        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
[02:22:08 WARN]:        at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
[02:22:08 WARN]:        at com.mysql.cj.protocol.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:398)
[02:22:08 WARN]:        ... 42 more

**Comment by TechnicallyCoded** [comment]
You probably enabled ssl on a localhost connection. That's a configuration issue I have seen multiple times.
