### ISSUE TITLE
I am unsure whats causing this

### ISSUE THREAD

**Issue by WeirdBlueDragon** [TechnicallyCoded/Inventory-Rollback-Plus#89]
when I open the roll back its invisible 
![image](https://user-images.githubusercontent.com/90156255/162415774-cc6c1ad5-c00d-44cd-ae00-2c23cd7b4c56.png)

**Comment by TechnicallyCoded** [comment]
Console logs please, otherwise, to me it just seems that you have no backups saved for that person

**Comment by WeirdBlueDragon** [comment]
09:58:36 WARN]: [InventoryRollbackPlus] Plugin InventoryRollbackPlus v1.6.6 generated an exception while executing task 50073
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Long.parseLong(Long.java:721) ~[?:?]
        at java.lang.Long.parseLong(Long.java:836) ~[?:?]
        at me.danjono.inventoryrollback.data.YAML.getSelectedPageTimestamps(YAML.java:146) ~[InventoryRollbackPlus-1.6.6.jar:?]
        at me.danjono.inventoryrollback.data.PlayerData.getSelectedPageTimestamps(PlayerData.java:99) ~[InventoryRollbackPlus-1.6.6.jar:?]
        at me.danjono.inventoryrollback.gui.menu.RollbackListMenu.showBackups(RollbackListMenu.java:84) ~[InventoryRollbackPlus-1.6.6.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-278]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-278]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-278]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:58:53 INFO]: CONSOLE issued server command: /xp give WeirdBlueDragon 1

**Comment by TechnicallyCoded** [comment]
Can you send me the player data file for the player you are trying to roll back pls?

**Comment by WeirdBlueDragon** [comment]
the entire server player data file?

**Comment by WeirdBlueDragon** [comment]
[1dc4f472-9f53-4235-b264-c9a294e57f3e.zip](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/files/8452975/1dc4f472-9f53-4235-b264-c9a294e57f3e.zip)

**Comment by TechnicallyCoded** [comment]
> the entire server player data file?

The player data file under plugins > inventryrollbackplus

**Comment by WeirdBlueDragon** [comment]
![image](https://user-images.githubusercontent.com/90156255/162485439-b6867379-f42d-4907-891f-0ae842dc55d8.png)

**Comment by TechnicallyCoded** [comment]
under backups

**Comment by WeirdBlueDragon** [comment]
[1646444542328.zip](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/files/8454256/1646444542328.zip)

**Comment by TechnicallyCoded** [comment]
Was that the only backup for that user?
