### ISSUE TITLE
Support: Corrupted Data

### ISSUE THREAD

**Issue by Ibotmealot** [TechnicallyCoded/Inventory-Rollback-Plus#93]
```[20:09:31 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: The skull profile is missing a name or textures!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.profile.CraftPlayerProfile.validateSkullProfile(CraftPlayerProfile.java:38) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.setOwnerProfile(CraftMetaSkull.java:224) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:58) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:201) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1793) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2142) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1730) ~[?:?]
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472) ~[?:?]
	at me.danjono.inventoryrollback.inventory.RestoreInventory.stacksFromBase64(RestoreInventory.java:69) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.inventory.RestoreInventory.getInventoryItems(RestoreInventory.java:34) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.data.YAML.getMainInventory(YAML.java:273) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.data.PlayerData.getMainInventory(PlayerData.java:282) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.gui.menu.MainInventoryBackupMenu.<init>(MainInventoryBackupMenu.java:47) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.listeners.ClickGUI$1.run(ClickGUI.java:217) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:09:31 ERROR]: [InventoryRollbackPlus] There was an error deserializing the material data. The data file is likely corrupted since this was saved on the same version the server is currently running on so it should have worked.
[20:09:45 INFO]: Ibotmealot issued server command: /irp restore real_god_
[20:09:47 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: The skull profile is missing a name or textures!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.profile.CraftPlayerProfile.validateSkullProfile(CraftPlayerProfile.java:38) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.setOwnerProfile(CraftMetaSkull.java:224) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:58) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:201) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1793) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2142) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1730) ~[?:?]
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472) ~[?:?]
	at me.danjono.inventoryrollback.inventory.RestoreInventory.stacksFromBase64(RestoreInventory.java:69) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.inventory.RestoreInventory.getInventoryItems(RestoreInventory.java:34) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.data.YAML.getMainInventory(YAML.java:273) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.data.PlayerData.getMainInventory(PlayerData.java:282) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.gui.menu.MainInventoryBackupMenu.<init>(MainInventoryBackupMenu.java:47) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.listeners.ClickGUI$1.run(ClickGUI.java:217) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:09:47 ERROR]: [InventoryRollbackPlus] There was an error deserializing the material data. The data file is likely corrupted since this was saved on the same version the server is currently running on so it should have worked.
[20:09:56 INFO]: Ibotmealot issued server command: /irp restore real_god_
[20:10:11 INFO]: Ibotmealot issued server command: /co lookup u:real_god_ t:1h r:5
[20:10:15 INFO]: Ibotmealot issued server command: /irp restore real_god_
[20:10:28 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta for deserialization	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1623]
java.lang.IllegalArgumentException: The skull profile is missing a name or textures!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.profile.CraftPlayerProfile.validateSkullProfile(CraftPlayerProfile.java:38) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.setOwnerProfile(CraftMetaSkull.java:224) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:58) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:201) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1793) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2142) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1730) ~[?:?]
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472) ~[?:?]
	at me.danjono.inventoryrollback.inventory.RestoreInventory.stacksFromBase64(RestoreInventory.java:69) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.inventory.RestoreInventory.getInventoryItems(RestoreInventory.java:34) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.data.YAML.getMainInventory(YAML.java:273) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.data.PlayerData.getMainInventory(PlayerData.java:282) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.gui.menu.MainInventoryBackupMenu.<init>(MainInventoryBackupMenu.java:47) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.listeners.ClickGUI$1.run(ClickGUI.java:217) ~[InventoryRollbackPlus-1.6.6.jar:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1623]	at java.lang.Thread.run(Thread.java:833) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

[20:10:28 ERROR]: [InventoryRollbackPlus] There was an error deserializing the material data. The data file is likely corrupted since this was saved on the same version the server is currently running on so it should have worked.
[20:10:29 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: The skull profile is missing a name or textures!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.profile.CraftPlayerProfile.validateSkullProfile(CraftPlayerProfile.java:38) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.setOwnerProfile(CraftMetaSkull.java:224) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:58) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at jdk.internal.reflect.GeneratedConstructorAccessor139.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:201) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1793) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2142) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1730) ~[?:?]
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]

	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472) ~[?:?]
	at me.danjono.inventoryrollback.inventory.RestoreInventory.stacksFromBase64(RestoreInventory.java:69) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.inventory.RestoreInventory.getInventoryItems(RestoreInventory.java:34) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.data.YAML.getMainInventory(YAML.java:273) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.data.PlayerData.getMainInventory(PlayerData.java:282) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.gui.menu.MainInventoryBackupMenu.<init>(MainInventoryBackupMenu.java:47) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at me.danjono.inventoryrollback.listeners.ClickGUI$1.run(ClickGUI.java:217) ~[InventoryRollbackPlus-1.6.6.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1623]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:10:29 ERROR]: [InventoryRollbackPlus] There was an error deserializing the material data. The data file is likely corrupted since this was saved on the same version the server is currently running on so it should have worked.```
What can I do to help mitigate this from happening again?

**Comment by TechnicallyCoded** [comment]
Please delete the corrupted saves and try again.
If you don't know how to just remove the ones that are corrupted, just delete all the backups for that player.
